// web-react/components/pages/profile/Profile.tsx
import link from "next/link";
import React from "react";
import useProfile from "../../../hooks/profile/useProfile";
import DefaultLayout from "../../../layouts/DefaultLayout";
import AppLink from "../../app/AppLink";
import ProfilePhoto from "../../pages/profile/ProfilePhoto";
import ProfileCoverPhoto from "./ProfileCoverPhoto";

interface ProfileProps {
  username: string;
}

const Profile: React.FC<ProfileProps> = ({ username }) => {
  const { links, response } = useProfile(username);

  const profile = response.data;

  if (response.isLoading) {
    return <>loading</>;
  }

  return (
    <div className="profile mb-4">
      <div className="container">
        <ProfileCoverPhoto coverPhoto={profile.coverPhoto} />

        <div className="profile__body">
          <ProfilePhoto photo={profile.profilePhoto} />
          <div className="profile__names">
            <h1 className="fullname">
              {profile.firstname} {profile.lastname}
            </h1>
            <p className="username">{{ username }}</p>
          </div>
        </div>

        <div className="profile__footer">
          <ul className="profile__tab">
            <li className="profile__tab-item">
              <AppLink href={links.profile} className="profile__tab-link">
                <span className="profile__tab-label"> Post </span>
                {/* <span className="profile__tab-count">{{ profile.postCount }}</span> */}
              </AppLink>
            </li>
            <li className="profile__tab-item">
              <AppLink href={links.about} className="profile__tab-link">
                <span className="profile__tab-label"> About </span>
              </AppLink>
            </li>
          </ul>
        </div>
      </div>

      {/* <change-profile-photos-modal /> */}
    </div>
  );
};

export default Profile;

// web/components/profile/Profile.vue
<template>
  <div class="profile mb-4">
    <div class="container">
      <div class="profile__cover">
        <img :src="profile.coverPhoto.url" alt="Cover photo" />

        <button-primary label="Change Cover Photo" :icon-left="icons.camera" />
      </div>

      <div class="profile__body">
        <div class="profile__photo">
          <div class="profile__photo-holder">
            <img :src="profile.profilePhoto.url" alt="Profile photo" />
          </div>
          <button-icon :icon="icons.camera" />
        </div>
        <div class="profile__names">
          <h1 class="fullname">
            {{ profile.firstname }} {{ profile.lastname }}
          </h1>
          <p class="username">@{{ profile.username }}</p>
        </div>
      </div>

      <div class="profile__footer">
        <ul class="profile__tab">
          <li class="profile__tab-item">
            <nuxt-link class="profile__tab-link" exact :to="links.profile">
              <span class="profile__tab-label"> Post </span>
              <span class="profile__tab-count">{{ postCount }}</span>
            </nuxt-link>
          </li>
          <li class="profile__tab-item">
            <nuxt-link class="profile__tab-link" exact :to="links.about">
              <span class="profile__tab-label"> About </span>
            </nuxt-link>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script>
import { mdiCamera } from "@mdi/js";
import profileMixin from "@/mixins/profile";
export default {
  mixins: [profileMixin],
  data() {
    return {
      icons: {
        camera: mdiCamera,
      },
    };
  },

  computed: {
    profile() {
      return this.$store.state.profile.current;
    },
    postCount() {
      return this.$store.state.profile.posts.count;
    },
  },

  //   middleware: "auth",
};
</script>

<style>
</style>
