// web-react/components/pages/profile/sub-pages/ProfilePost.tsx
import React from "react";
import { PlusIcon } from "../../../../configs/Icons";
import useProfilePost from "../../../../hooks/profile/useProfilePost";
import Button from "../../../buttons/Button";
import PostCard from "../../../post/PostCard";

interface ProfilePostProps {
  username: string;
}

const ProfilePost: React.FC<ProfilePostProps> = ({ username }) => {
  const response = useProfilePost(username);

  //   console.log(posts);

  if (response.isLoading) return <div>Loading...</div>;

  const posts = response.data;

  if (posts.count === 0) return <div>No Post Yet</div>;

  return (
    <div className="container mt-3 pb-5">
      <div className="row">
        {posts.items.map((item) => (
          <div key={item.id} className="col-20 mb-2">
            {<PostCard post={item} />}
          </div>
        ))}
      </div>

      <Button color="primary" size="large" icon fab={true}>
        <PlusIcon />
      </Button>
    </div>
  );
};

export default ProfilePost;

// web/components/profile/ProfilePost.vue
<template>
  <div class="container mt-3 pb-5">
    <div class="row">
      <div v-for="item in posts" :key="item.id" class="col-3">
        <card-post :post="item" />
      </div>
    </div>

    <button-icon to="/new" size="xl" variant="primary" fab :icon="icons.plus" />
  </div>
</template>

<script>
import { mdiPlus } from "@mdi/js";
import { types } from "@/store/types";
export default {
  data() {
    return {
      icons: {
        plus: mdiPlus,
      },
    };
  },
  computed: {
    posts() {
      return this.$store.state.profile.posts.items;
    },
  },
  async fetch() {
    const params = this.$route.params;
    await this.$store.dispatch("profile/" + types.actions.FETCH_PROFILE_POSTS, {
      username: params.username,
    });
  },
};
</script>

<style>
</style>
