// web-vue/components/profile/ProfilePost.vue
<template>
  <div class="container mt-3 pb-5">
    <app-errors v-if="postCount === 0 && $auth.loggedIn" error="me-no-post" />
    <app-errors v-else-if="postCount === 0" error="user-no-post" />
    <template v-else>
      <div class="row">
        <div v-for="item in posts.items" :key="item.id" class="col-20 mb-2">
          <card-post :post="item" />
        </div>
      </div>

      <button-icon
        v-if="loggedIn"
        to="/new"
        size="xl"
        variant="primary"
        fab
        :icon="icons.plus"
      />
    </template>
  </div>
</template>

<script>
import { mdiPlus } from "@mdi/js";
import { types } from "@/store/types";
import profileMixin from "@/mixins/profile";
export default {
  mixins: [profileMixin],
  data() {
    return {
      icons: {
        plus: mdiPlus,
      },
    };
  },

  computed: {
    postCount() {
      return parseInt(this.$store.state.profile.current.postCount);
    },
  },
  async fetch() {
    const username = this.$route.params.username;

    if (!username);
    await this.fetchPost(username);
  },

  watch: {
    $route: "$fetch",
  },
};
</script>

<style>
</style>

// web-react/components/pages/profile/sub-pages/ProfilePost.tsx
import React from "react";
import { PlusIcon } from "../../../../configs/Icons";
import { useAuthContext } from "../../../../context/AuthContext";
import useProfilePost from "../../../../hooks/profile/useProfilePost";
import AppError from "../../../app/AppError";
import Button from "../../../buttons/Button";
import PostCard from "../../../post/PostCard";

interface ProfilePostProps {
  username: string;
}

const ProfilePost: React.FC<ProfilePostProps> = ({ username }) => {
  const { user } = useAuthContext();

  const response = useProfilePost(username);

  //   console.log(posts);

  if (response.isLoading) return <div>Loading...</div>;

  const posts = response.data;

  if (posts.count === 0) {
    if (user.username === username) {
      return <AppError error="me-no-post" />;
    }

    return <AppError error="user-no-post" />;
  }

  return (
    <div className="container mt-3 pb-5">
      <div className="row">
        {posts.items.map((item) => (
          <div key={item.id} className="col-20 mb-2">
            {<PostCard post={item} />}
          </div>
        ))}
      </div>

      <Button color="primary" size="large" icon fab={true}>
        <PlusIcon />
      </Button>
    </div>
  );
};

export default ProfilePost;
