// web-react/components/card/Card.tsx
import React from "react";
import ProgressLinear from "../progress/ProgressLinear";

interface CardProps {
  rounded?: boolean;
  elevate?: boolean;
  loading?: boolean;
}

const Card: React.FC<CardProps> = ({ rounded, elevate, loading, children }) => {
  const classlist = ["card"];

  if (rounded) classlist.push("card--rounded");
  if (elevate) classlist.push("card--elevate");

  return (
    <div className={classlist.join(" ")}>
      {loading && <ProgressLinear />}
      {children}
    </div>
  );
};

export default Card;

// web-vue/components/cards/basics/Card.vue
<template>
  <div class="card" :class="[roundedClass, elevateClass]">
    <progress-linear v-if="loading" />
    <slot></slot>
  </div>
</template>

<script>
export default {
  props: {
    rounded: Boolean,
    elevate: Boolean,
    loading: Boolean,
  },

  computed: {
    elevateClass() {
      return this.elevate ? "card--elevate" : "";
    },
    roundedClass() {
      return this.rounded ? "card--rounded" : "";
    },
  },
};
</script>

<style>
</style>
