// web-react/components/snackbar/Snackbar.tsx
import React, { ReactNode, useEffect, useState } from "react";
import { CloseIcon } from "../../configs/Icons";
import { SnackbarConfig } from "../../context/SnackbarContext";
import AppImage from "../app/AppImage";
import AppLink from "../app/AppLink";
import Button from "../buttons/Button";

type SnackbarProps = {
  config: SnackbarConfig;
};

const barTypes = {
  success: "snackbar--success",
  error: "snackbar--error",
  warning: "snackbar--warning",
};

const Snackbar: React.FC<SnackbarProps> = ({ config }) => {
  const { show, type, timeout, image, title, body, showClose, link } = config;
  const [_show, _setShow] = useState(false);
  const classlist = ["snackbar"];

  useEffect(() => {
    console.log("USE_EFFECT_UPDATED_CONFIG", config);
    _setShow(config.show);
  }, [config]);

  if (type) {
    classlist.push(barTypes[type]);
  }
  if (timeout) {
    setTimeout(() => _setShow(false), timeout);
  }

  const close = () => {
    console.log("Closing");
    _setShow(false);
  };

  const renderContent = () => {
    return (
      <>
        {image && (
          <div className="snackbar__icon">
            <AppImage src={image}></AppImage>
          </div>
        )}

        <div className="snackbar__body">
          <div className="snackbar__title">{title}</div>
          <div className="snackbar__description">{body}</div>
        </div>

        {showClose && (
          <div className="snackbar__action">
            <Button icon color="secondary" onClick={close}>
              <CloseIcon />
            </Button>
          </div>
        )}
      </>
    );
  };

  const className = classlist.join(" ");

  if (!_show) return null;

  return link ? (
    <AppLink className={className} href={link}>
      {renderContent()}
    </AppLink>
  ) : (
    <div className={className}>{renderContent()}</div>
  );
};

export default Snackbar;

// web/components/snackbars/Snackbar.vue
<template>
  <div v-if="config.show" class="snackbar" :class="[showClass, typeClass]">
    <component
      :is="config.link ? 'nuxt-link' : 'div'"
      :to="config.link"
      v-if="config.image"
      class="snackbar__icon"
    >
      <img :src="config.image" alt="Post" />
    </component>
    <div class="snackbar__body">
      <h1 class="snackbar__title">{{ config.title }}</h1>

      <p class="snackbar__description">
        {{ config.body }}
      </p>
    </div>

    <div class="snackbar__action">
      <button-icon
        v-if="config.showClose"
        :icon="icons.close"
        @click.native="hide"
      />
    </div>
  </div>
</template>

<script>
import { mdiClose } from "@mdi/js";
import { types } from "@/store/types";

const barTypes = {
  success: "snackbar--success",
  error: "snackbar--error",
  warning: "snackbar--warning",
};

export default {
  data() {
    return {
      icons: {
        close: mdiClose,
      },
    };
  },

  computed: {
    config() {
      return this.$store.state.frontend.snackbars;
    },

    showClass() {
      return this.config.show ? "snackbar--show" : null;
    },

    typeClass() {
      return barTypes[this.config.type];
    },
  },

  methods: {
    hide() {
      return this.$store.dispatch(types.actions.HIDE_SNACKBAR);
    },
  },
};
</script>

<style>
</style>
