// web-vue/components/profile/ProfilePhoto.vue
<template>
  <div class="profile__photo-holder">
    <img :src="src" alt="Profile photo" />
  </div>
</template>

<script>
export default {
  props: {
    url: {
      type: String,
    },
  },

  computed: {
    src() {
      return this.url ? this.url : require("@/assets/img/blank-profile.png");
    },
  },
};
</script>

<style>
</style>

// web-react/components/pages/profile/ProfilePhoto.tsx
import React from "react";
import AppImage from "../../app/AppImage";
import BlankProfileImage from "@/assets/img/blank-profile.png";
interface ProfilePhotoProps {
  photo: Photo;
}

const ProfilePhoto: React.FC<ProfilePhotoProps> = ({ photo }) => {
  const photoUrl = photo.securedUrl || BlankProfileImage.src;

  return (
    <div className="profile__photo">
      <div className="profile__photo-holder">
        <AppImage src={photoUrl} layout="fill" />
      </div>
    </div>
  );
};

export default ProfilePhoto;
