// web-vue/components/forms/LoginForm.vue
<template>
  <!--  -->
  <div class="card--form">
    <div class="card--form__header">
      <div class="card--form__logo">
        <app-logo />
      </div>
    </div>
    <app-alert type="error" :alert.sync="alert" class="mb-2"></app-alert>
    <validation-observer ref="form" v-slot="{ handleSubmit }">
      <form @submit.prevent="handleSubmit(onSubmit)">
        <div class="card--form__body mb-2">
          <div class="row">
            <div class="col-12 mb-2">
              <input-field
                v-model="credential.usernameOrEmail"
                :rules="rules.usernameOrEmail"
                label="Username"
                id="username"
                name="email"
              ></input-field>
            </div>
            <div class="col-12 mb-1">
              <password-field
                :show-toggle="true"
                v-model="credential.password"
                :rules="rules.password"
                label="Password"
                id="password"
                name="password"
              ></password-field>
            </div>
            <!-- <div class="col-12">
              <checkbox-field
                v-model="credential.rememberMe"
                label="Remember me"
                id="rememberMe"
              ></checkbox-field>
            </div> -->
          </div>
        </div>

        <div class="card--form__action">
          <button-primary
            label="Login"
            type="submit"
            name="login"
            :is-full-width="true"
            size="lg"
          />
        </div>
      </form>
    </validation-observer>

    <p class="card--form__have-account">
      Don't have an account?
      <nuxt-link class="btn--links" to="/register">Sign Up</nuxt-link>
    </p>

    <div class="card--form__forgot">
      <!-- <nuxt-link class="btn--links" to="/forgot-password"
        >Forgot Password</nuxt-link
      > -->
    </div>
  </div>
</template>

<script>
import { ValidationProvider, ValidationObserver } from "vee-validate";
export default {
  components: {
    ValidationProvider,
    ValidationObserver,
  },
  data() {
    return {
      rules: {
        usernameOrEmail: "required",
        password: "required",
      },
      credential: {
        usernameOrEmail: "", //topzdev123
        password: "", //123456789
        // rememberMe: false,
      },
      alert: {
        message: null,
        show: false,
      },
    };
  },
  methods: {
    async onSubmit() {
      try {
        const response = await this.$auth.login({
          data: this.credential,
        });

        console.log(this.$auth.user);

        if (this.$auth.loggedIn) {
          // this.$router.push("/profile/" + this.$auth.user.username);
        }
      } catch (error) {
        console.log(error);

        if (error.response && error.response.data) {
          const data = error.response.data;
          this.alert = {
            message: data.error.message,
            show: true,
          };
        }
      } finally {
        this.credential = {
          usernameOrEmail: "",
          password: "",
        };
      }
    },
  },
};
</script>

<style>
</style>

// web-react/components/forms/LoginForm.tsx
import { signIn } from "next-auth/react";
import { useRouter } from "next/router";
import React, { useCallback, useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { EyeOpenIcon, EyeCloseIcon } from "../../configs/Icons";
import AppAlert from "../app/AppAlert";
import AppLink from "../app/AppLink";
import AppLogo from "../app/AppLogo";
import Button from "../buttons/Button";
import TextField from "../inputs/TextField";

interface LoginFormProps {}

type LoginCredentials = {
  emailOrUsername: string;
  password: string;
};

const LoginForm: React.FC<LoginFormProps> = ({}) => {
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<LoginCredentials>({});

  const [showPassword, setShowPassword] = useState(false);

  const onSubmit: SubmitHandler<LoginCredentials> = async (credentials) => {
    const { ok, error } = await signIn("credentials", {
      password: credentials.password,
      usernameOrEmail: credentials.emailOrUsername,
    });
    console.log(credentials);

    if (error) {
      console.error(error);
    }

    if (ok) {
      console.log(ok);
    }
    console.log(credentials);

    // signIn("credentials", {
    //   password: credentials.password,
    //   usernameOrEmail: credentials.emailOrUsername,
    //   redirect: false,
    // });
    // signIn("credentials", credentials);
  };

  const onTogglePassword = useCallback(() => {
    setShowPassword((state) => !state);
  }, [setShowPassword]);

  console.log(errors, showPassword);

  return (
    <div className="card--form">
      <div className="card--form__header">
        <div className="card--form__logo">
          <AppLogo href="/" />
        </div>

        <AppAlert type="error" message="test" />
      </div>
      <form onSubmit={handleSubmit(onSubmit)}>
        <div className="card--form__body mb-1">
          <div className="row">
            <div className="col-12 mb-2">
              <TextField
                {...register("emailOrUsername", {
                  required: "Usernanme or Email address is required",
                })}
                label="Username or Email Addresss"
                required
                error={errors.emailOrUsername?.message}
              />
            </div>
            <div className="col-12 mb-1">
              <TextField
                {...register("password", {
                  required: "Password is required",
                })}
                type={showPassword ? "text" : "password"}
                iconRight={showPassword ? <EyeOpenIcon /> : <EyeCloseIcon />}
                iconRightFunc={onTogglePassword}
                label="Password"
                required
                error={errors.password?.message}
              />
            </div>
          </div>
        </div>
        <div className="card--form__action mb-3">
          <Button
            type="submit"
            block
            size="large"
            className="ml-auto"
            loading={isSubmitting}
          >
            Login
          </Button>
        </div>

        <p className="text--primary mt-2 mb-3 align-center">
          <AppLink href={"/forgot-password"}>
            <a className="link" style={{ marginLeft: 5 }}>
              Forgot Password
            </a>
          </AppLink>
        </p>
      </form>
    </div>
  );
};

export default LoginForm;
