// web-react/components/search/SearchSelect.tsx
import React, { useState } from "react";
import { ArrowDownIcon } from "../../configs/Icons";
import ClickOutside from "../utils/ClickOutside";

export interface SearchSelectOptions {
  id: string;
  text: string;
}

interface SearchSelectProps {
  value: string | number;
  itemValue: string;
  itemText: string;
  options: SearchSelectOptions[];
  label: string;
  onSelected: (value: any) => void;
}

const SearchSelect: React.FC<SearchSelectProps> = ({
  itemValue,
  itemText,
  options,
  label,
  value,
  onSelected,
}) => {
  const [show, setShow] = useState(false);
  const classlist = ["search-select", show ? "show" : ""];
  const selectValue = (item: any) => {
    return itemValue ? item[itemValue] : item;
  };
  const selectText = (item: any) => {
    return itemText ? item[itemText] : item;
  };

  const displayText = () => {
    if (options.length && itemValue !== undefined) {
      return (options as any).filter(
        (item: any) => item[itemValue] === value
      )[0].text;
    } else {
      return value;
    }
  };

  return (
    <div
      onClick={() => setShow((state) => !state)}
      className={classlist.join(" ")}
    >
      <div className="search-select__body">
        <div className="search-select__value">{displayText()}</div>

        <div className="search-select__label">{label}</div>

        <div className="search-select__arrow">
          <ArrowDownIcon />
        </div>
      </div>

      <ul className="search-select__list">
        <ClickOutside open={show} setClose={setShow}>
          {options.map((item) => (
            <li
              className={selectValue(item) === value ? "active" : ""}
              key={selectValue(item)}
              onClick={() => onSelected((item as any)[itemValue])}
            >
              {selectText(item)}
            </li>
          ))}
        </ClickOutside>
      </ul>
    </div>
  );
};

export default SearchSelect;

// web/components/search/SearchSelect.vue
<template>
  <div
    :class="['search-select', show ? 'show' : '']"
    @click="show = !show"
    v-click-outside="hide"
  >
    <div class="search-select__body">
      <div class="search-select__value">{{ displayText }}</div>

      <div class="search-select__label">{{ label }}</div>

      <div class="search-select__arrow">
        <app-icon :path="icons.arrow"></app-icon>
      </div>
    </div>

    <ul class="search-select__list">
      <li
        v-for="item in options"
        :key="item.id"
        @click="selected(selectValue(item))"
        :class="selectValue(item) === value ? 'active' : ''"
      >
        {{ selectText(item) }}
      </li>
    </ul>
  </div>
</template>

<script>
import { mdiMenuDown } from "@mdi/js";

export default {
  props: {
    value: [String, Number],
    itemValue: String,
    itemText: String,
    options: Array,
    label: String,
  },
  data() {
    return {
      show: false,
      icons: {
        arrow: mdiMenuDown,
      },
    };
  },

  computed: {
    displayText() {
      if (this.options.length)
        return this.options.filter(
          (item) => item[this.itemValue] === this.value
        )[0][this.itemText];
    },
  },

  methods: {
    selected($value) {
      console.log($value);
      this.$emit("input", $value);
    },

    selectValue(item) {
      return this.itemValue ? item[this.itemValue] : item;
    },
    selectText(item) {
      return this.itemText ? item[this.itemText] : item;
    },

    hide() {
      this.show = false;
    },
  },
};
</script>

<style>
</style>
