// web-react/components/search/SearchBarInput.tsx
import React from "react";
import { SearchIcon } from "../../config/Icons";

type SearchBarInputProps = {} & React.DetailedHTMLProps<
  React.InputHTMLAttributes<HTMLInputElement>,
  HTMLInputElement
>;

const SearchBarInput: React.FC<SearchBarInputProps> = ({ ...rest }) => {
  return (
    <div className="search-bar-input">
      <div className="inp--search">
        <SearchIcon className="search-bar-input__icon" />
        <input {...rest} className="inp inp--search__inp" type="text" />
        {rest.value === "" && (
          <label className="inp--search__placeholder">
            <span className="p-default">Search post like</span>
            <span className="p-dynamic">
              {'"Looking for keyboard swap to mouse"'}
            </span>
          </label>
        )}
      </div>
    </div>
  );
};

export default SearchBarInput;

// web/components/search/SearchBarInput.vue
<template>
  <div class="search-bar-input">
    <div class="inp--search">
      <app-icon
        class="search-bar-input__icon"
        type="mdi"
        :path="icons.search"
      />
      <input v-model="value" class="inp inp--search__inp" type="text" />
      <label v-if="isEmpty" for="" class="inp--search__placeholder"
        ><span class="p-default">Search post like</span>
        <span class="p-dynamic">"Looking for keyboard swap to mouse"</span>
      </label>
    </div>
  </div>
</template>

<script>
import { mdiMagnify } from "@mdi/js";
export default {
  //   props: {
  //     value: String,
  //   },
  data() {
    return {
      value: "",
      icons: {
        search: mdiMagnify,
      },
    };
  },
  computed: {
    isEmpty() {
      return this.value === "";
    },
  },
};
</script>

<style>
</style>
