// web-vue/components/profile/ProfilePhoto.vue
<template>
  <div class="profile__photo-holder">
    <img :src="src" alt="Profile photo" />
  </div>
</template>

<script>
export default {
  props: {
    url: {
      type: String,
    },
  },

  computed: {
    src() {
      return this.url ? this.url : require("@/assets/img/blank-profile.png");
    },
  },
};
</script>

<style>
</style>

// web-react/components/profile/ProfilePhoto.tsx
import React from "react";
import AppImage from "../app/AppImage";
import blankProfileImage from "@/assets/img/blank-profile.png";

interface ProfilePhotoProps {
  url?: string;
}

const ProfilePhoto: React.FC<ProfilePhotoProps> = ({ url }) => {
  let profileSrc: any = url;

  if (!url) {
    profileSrc = blankProfileImage;
  }

  return (
    <div className="profile__photo-holder">
      <AppImage src={profileSrc} alt="Profile Photo" />
    </div>
  );
};

export default ProfilePhoto;
