// web-react/components/app/AppAlert.tsx
import React, { useState } from "react";
import {
  CloseIcon,
  ErrorIcon,
  InfoIcon,
  SuccessIcon,
  WarningIcon,
} from "../../configs/Icons";

export interface AppAlertProps {
  type: "info" | "error" | "warning" | "success" | string;
  message: string;
  show?: boolean;
  timeout?: number;
}

const alertIcons = {
  info: <InfoIcon />,
  error: <ErrorIcon />,
  warning: <WarningIcon />,
  success: <SuccessIcon />,
};

const AppAlert: React.FC<AppAlertProps> = ({
  show,
  message,
  type,
  timeout,
}) => {
  const classlist = ["alert"];
  const [_show, _setShow] = useState(show);

  const close = () => {
    _setShow(false);
  };

  if (show && timeout) {
    setTimeout(() => {
      _setShow(false);
    }, timeout);
  }

  if (type) {
    classlist.push(`alert--${type}`);
  }

  return show ? (
    <div className={classlist.join(" ")}>
      <div className="alert__icon">{alertIcons[type]}</div>

      <div className="alert__message">{message}</div>

      <button className="alert__exit" onClick={close}>
        <CloseIcon />
      </button>
    </div>
  ) : (
    <></>
  );
};

AppAlert.defaultProps = {
  show: false,
};

export default AppAlert;

// web/components/alerts/AppAlert.vue
<template>
  <div :class="setAlertClass" v-if="alert.show">
    <div class="alert__icon">
      <app-icon type="mdi" :path="iconType" />
    </div>

    <div class="alert__message">
      <slot>{{ alert.message }}</slot>
    </div>

    <button @click="close" class="alert__exit">
      <app-icon type="mdi" :path="icons.close" />
    </button>
  </div>
</template>

<script>
import {
  mdiInformation,
  mdiAlert,
  mdiAlertCircle,
  mdiCheckCircle,
  mdiClose,
} from "@mdi/js";
export default {
  data() {
    return {
      icons: {
        info: mdiInformation,
        error: mdiAlertCircle,
        warning: mdiAlert,
        success: mdiCheckCircle,
        close: mdiClose,
      },
    };
  },
  props: {
    alert: {
      type: Object,
      default: () => ({
        message: null,
        show: false,
        type: "info",
        timeout: undefined,
      }),
    },
    type: {
      type: String,
    },
    message: {
      type: String,
    },
  },

  watch: {
    alert(newValue) {
      const self = this;

      if (newValue.show === true && newValue.timeout !== undefined) {
        setTimeout(function () {
          self.close();
        }, newValue.timeout);
      }
    },
  },

  computed: {
    alertType() {
      return this.type || this.alert.type;
    },
    setAlertClass() {
      return `alert ${this.alertType ? `alert--${this.alertType}` : ""} `;
    },

    iconType() {
      return this.icons[this.alertType];
    },
  },

  methods: {
    close() {
      this.alert.show = false;
    },
  },
};
</script>

<style>
</style>
